# How to use:
# -----------------------------------------------------------------------------
# - how to install gem
#   $ bundle install {gem name}
#
# - Runing Jekyll server
#   $ bundle exec jekyll s
# -----------------------------------------------------------------------------

# Setup
title:            'Rendang.org'
tagline:          'A curated of tech articles with rendang (delicious) taste'
description:      'All tech with helpfull information'
url:              https://rendang.org'

defaults:
  -
    scope:
      path: 'README.md'
    values:
      permalink: 'index.html'

theme: jekyll-theme-minimal